/**
 * PDF Exporter - Generates PDF from sheet music notation
 */

import { midiToNoteName, formatTime, timeToPosition } from '../utils/musicTheory';

export class PDFExporter {
    /**
     * Export the current score as a PDF
     */
    static async exportPDF(notes, measures, instrument, tempo, timeSignature, keySignature, fileName) {
        // Dynamic import jsPDF
        const { default: jsPDF } = await import('jspdf');

        const doc = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a4',
        });

        const pageWidth = 210;
        const pageHeight = 297;
        const margin = 20;
        const staffWidth = pageWidth - 2 * margin;
        const staffSpacing = 30;
        let y = margin;

        // Title
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(20);
        doc.text(fileName || 'Untitled Score', pageWidth / 2, y, { align: 'center' });
        y += 10;

        // Subtitle info
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(120, 120, 120);
        doc.text(
            `${instrument.name} | ${timeSignature.num}/${timeSignature.den} | Key: ${keySignature} | ♩= ${tempo}`,
            pageWidth / 2, y, { align: 'center' }
        );
        doc.setTextColor(0, 0, 0);
        y += 15;

        // Draw staves with notes
        const notesPerLine = Math.max(8, Math.floor(staffWidth / 8));
        const noteGroups = [];

        for (let i = 0; i < notes.length; i += notesPerLine) {
            noteGroups.push(notes.slice(i, i + notesPerLine));
        }

        for (const group of noteGroups) {
            if (y > pageHeight - margin - staffSpacing) {
                doc.addPage();
                y = margin;
            }

            // Draw 5 staff lines
            doc.setDrawColor(180, 180, 180);
            doc.setLineWidth(0.3);
            for (let line = 0; line < 5; line++) {
                const lineY = y + line * 2.5;
                doc.line(margin, lineY, margin + staffWidth, lineY);
            }

            // Draw notes on staff
            const noteSpacing = staffWidth / (group.length + 1);
            group.forEach((note, i) => {
                const x = margin + noteSpacing * (i + 1);
                const noteY = this.getNoteYPosition(note.midi, y);

                // Note head (filled ellipse)
                doc.setFillColor(40, 40, 40);
                doc.ellipse(x, noteY, 2, 1.5, 'F');

                // Stem
                doc.setLineWidth(0.5);
                doc.setDrawColor(40, 40, 40);
                if (noteY > y + 5) {
                    doc.line(x + 2, noteY, x + 2, noteY - 10);
                } else {
                    doc.line(x - 2, noteY, x - 2, noteY + 10);
                }

                // Note name below
                doc.setFontSize(6);
                doc.setTextColor(100, 100, 150);
                doc.text(note.noteName, x, y + 18, { align: 'center' });
            });

            y += staffSpacing;
        }

        // Footer
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by AutoScore', pageWidth / 2, pageHeight - 10, { align: 'center' });

        // Save
        const safeName = (fileName || 'autoscore-export').replace(/[^a-zA-Z0-9-_ ]/g, '');
        doc.save(`${safeName}.pdf`);
    }

    /**
     * Map MIDI note to Y position on the staff
     */
    static getNoteYPosition(midi, staffTop) {
        // Middle C (60) sits on the first ledger line below treble staff
        // Each staff line/space = 1.25mm
        const middleCY = staffTop + 12.5; // Below the staff
        const semitoneToStaff = {
            0: 0, 1: 0, 2: 1, 3: 1, 4: 2, 5: 3, 6: 3,
            7: 4, 8: 4, 9: 5, 10: 5, 11: 6,
        };

        const noteInOctave = midi % 12;
        const octave = Math.floor(midi / 12) - 5; // Octave relative to middle C's octave
        const staffPosition = semitoneToStaff[noteInOctave] + octave * 7;
        const y = middleCY - staffPosition * 1.25;

        return Math.max(staffTop - 5, Math.min(staffTop + 20, y));
    }
}
